# Generated by Django 6.1.1 on 2026-09-27 05:21

import django.core.validators
import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="商品名")),
                (
                    "rakuten_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="楽天市場商品URL",
                    ),
                ),
                (
                    "qr_token",
                    models.CharField(
                        db_index=True,
                        default=inventory.models.generate_qr_token,
                        max_length=64,
                        unique=True,
                        verbose_name="QRトークン",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="現在庫",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="有効フラグ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("USE", "商品使用"),
                            ("RESTOCK", "自動補充"),
                            ("ADJUST", "在庫調整"),
                        ],
                        max_length=10,
                        verbose_name="変更種別",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="変動数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_histories",
                        to="inventory.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "在庫変更履歴",
                "verbose_name_plural": "在庫変更履歴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RestockSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="補充数量"),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="補充予定日時")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="処理済みフラグ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restock_schedules",
                        to="inventory.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "自動補充予定",
                "verbose_name_plural": "自動補充予定",
                "ordering": ["scheduled_at"],
            },
        ),
    ]
